### ISSUE TITLE
You get undefined in _redirects file

### ISSUE THREAD

**Issue by devotox** [shipshapecode/ember-cli-netlify#10]

**Comment by RobbieTheWagner** [comment]
@devotox what? Can you provide more details please.

**Comment by devotox** [comment]
I went through the exact steps from your Readme on ember 3.10.1
added this to redirects `/*    /index.html   200`

and the output in _redirects is
`undefined/*    /index.html   200`

**Comment by RobbieTheWagner** [comment]
@devotox can you share the project, so I can debug?

**Comment by devotox** [comment]
https://github.com/devotox/zero-cost-web-app

**Comment by devotox** [comment]
dont mind the fact i put an empty string before the redirect in ember-cli-build.js. That is what made it work for me

**Comment by RobbieTheWagner** [comment]
@devotox why not use a `.netlifyredirects` file? That should work. We must have a bug with the `ember-cli-build.js` approach somewhere. This reproduction is helpful, I will work on a fix.

**Comment by devotox** [comment]
@rwwagner90 Alright will do. Thank you

**Comment by RobbieTheWagner** [comment]
@devotox can you try 0.3.0?

**Comment by devotox** [comment]
Yup that seems to work. Thank you for the quick turnaround
